version = 0.1

[default.deploy.parameters]
region = "us-east-1"
capabilities = ["CAPABILITY_IAM", "CAPABILITY_NAMED_IAM"]
confirm_changeset = true
resolve_s3 = true

[stg.deploy.parameters]
stack_name = "gbm-connect-bootstrap-stg"
s3_bucket = "gbm-connect-sam-artifacts-stg"
parameter_overrides = [
  "Environment=stg",
  "PipelineRoleArn=arn:aws:iam::825765398662:role/gbm-connect-pipeline-stg-role",
  "BuildRoleArn=arn:aws:iam::825765398662:role/gbm-connect-build-stg-role",
  "ReleaseRoleArn=arn:aws:iam::825765398662:role/gbm-connect-release-role"
]