AWSTemplateFormatVersion: '2010-09-09'
Description: S3 Buckets for CodePipeline Artifacts

Parameters:
  Environment:
    Type: String
    AllowedValues: [stg, prd]

Resources:
  ArtifactBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "gbm-connect-artifacts-${Environment}-${AWS::Region}"
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

Outputs:
  ArtifactBucketName:
    Value: !Ref ArtifactBucket
    Export:
      Name: !Sub "gbm-connect-artifacts-${Environment}-name"
