AWSTemplateFormatVersion: '2010-09-09'
Description: S3 Buckets for GBM Connect artifacts

Parameters:
  Environment:
    Type: String
    AllowedValues: [stg, prd]
    Description: Environment name

Resources:
  ArtifactsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "gbm-connect-artifacts-${Environment}"
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldVersions
            Status: Enabled
            NoncurrentVersionExpirationInDays: 30

Outputs:
  BucketName:
    Description: Artifacts bucket name
    Value: !Ref ArtifactsBucket
    Export:
      Name: !Sub "${AWS::StackName}-ArtifactsBucket"