AWSTemplateFormatVersion: '2010-09-09'
Description: CI/CD Pipeline for GBM Connect - Staging

Parameters:
  GitHubOwner:
    Type: String
    Default: "mmacchia-nubity"
  GitHubRepo:
    Type: String
    Default: "pser-gbm-sfdc-integration"
  PipelineRoleArn:
    Type: String
  BuildRoleArn:
    Type: String
  ReleaseRoleArn:
    Type: String
  ArtifactsBucket:
    Type: String
  GitHubToken:
    Type: String
    Description: Plain GitHub token read from SSM (decrypted by OIDC role)

Resources:
  GBMConnectCodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: gbm-connect-codebuild-stg
      ServiceRole: !Ref BuildRoleArn
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:7.0
        PrivilegedMode: true
        EnvironmentVariables:
          - Name: STAGE
            Value: stg
          - Name: ACCOUNT
            Value: !Ref AWS::AccountId
      Source:
        Type: CODEPIPELINE
        BuildSpec: buildspec-stg.yml
      TimeoutInMinutes: 30

  GBMConnectReleaseProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: gbm-connect-release-stg
      ServiceRole: !Ref ReleaseRoleArn
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:7.0
        EnvironmentVariables:
          - Name: GITHUB_TOKEN
            Value: !Ref GitHubToken
      Source:
        Type: CODEPIPELINE
        BuildSpec: buildspec-release.yml

  GBMConnectPipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: gbm-connect-pipeline-stg
      RoleArn: !Ref PipelineRoleArn
      ArtifactStore:
        Type: S3
        Location: !Ref ArtifactsBucket
      Stages:
        - Name: source
          Actions:
            - Name: source-gbm-connect
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Version: '1'
                Provider: GitHub
              Configuration:
                Owner: !Ref GitHubOwner
                Repo: !Ref GitHubRepo
                Branch: pser-29-deploy-test
                PollForSourceChanges: false
                OAuthToken: !Ref GitHubToken
              OutputArtifacts:
                - Name: SourceGBMConnect
        - Name: deploy
          Actions:
            - Name: deploy-gbm-connect
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: '1'
                Provider: CodeBuild
              Configuration:
                ProjectName: !Ref GBMConnectCodeBuildProject
              InputArtifacts:
                - Name: SourceGBMConnect

        - Name: approval # desde aca se cambia para tags
          Actions:
            - Name: manual-approval
              ActionTypeId:
                Category: Approval
                Owner: AWS
                Version: '1'
                Provider: Manual
              Configuration:
                CustomData: '{"create_release": true}'
              RunOrder: 1 # hasta aca se cambia para tags

        - Name: release
          Actions:
            - Name: create-release-tag
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: '1'
                Provider: CodeBuild
              Configuration:
                ProjectName: !Ref GBMConnectReleaseProject
              InputArtifacts:
                - Name: SourceGBMConnect
              RunOrder: 2

  GBMConnectWebhook:
    Type: AWS::CodePipeline::Webhook
    Properties:
      Authentication: GITHUB_HMAC
      AuthenticationConfiguration:
        SecretToken: !Ref GitHubToken
      Filters:
        - JsonPath: "$.ref"
          MatchEquals: "refs/heads/pser-29-deploy-test"
      TargetPipeline: !Ref GBMConnectPipeline
      TargetAction: source-gbm-connect
      TargetPipelineVersion: !GetAtt GBMConnectPipeline.Version
      RegisterWithThirdParty: true
